### ISSUE TITLE
Alter content and order of sidebar burger menu

### ISSUE THREAD

**Issue by iteles** [mosteirodelandim/landim-website#1]
Following a review of the site contents and sections as a family, the following alterations are required to the sidebar menu:

The sidebar menu should contain the following sections in the following order [Portuguese / English ]:
+ [x] Início / Home **[Unchanged]**
+ [x] Quem Somos / About Us **[New section, separate issue to be opened on content]**
+ [x] Serviços / Services **[Unchanged for now - a new issue will be opened on a change in title]**
+ [x] Fotografias / Photo Gallery **[Name change in English]**
+ [x] História / History **[New position in the hierarchy]**
+ [x] Jardins / Gardens **[New section, separate issue to be opened on content]**
+ [x] Vinho & Vinhas / Wine and Vineyard **[New name in both languages]**
+ [x] FAQs **[New section in menu, already exists as a page]**
+ [x] Contactos / Contact Us **[New section in menu, already exists as a page]**

Note: The 'Stay' portion of the website will be brought back but is currently on hold whilst we await legalization of the accommodation.

**Comment by LuchoTurtle** [comment]
The "About Us" part doesn't really make section, does it? Isn't it a quick tile on the landing page just to introduce us? Are we going to have a dedicated page just talking about us? @iteles

**Comment by iteles** [comment]
@LuchoTurtle No, the 'About Us' isn't just a tile, it'll be a separate page that needs to be written!

On the 'Contact Us', I reckon for now we can just link to the footer. Eventually we may want to link to the bottom of the FAQ page but we'll tidy that up a bit first.

**Comment by iteles** [comment]
The 'Wine & Stay' item in the sidebar menu hasn't been changed to 'Wine & Vineyards' yet (at least not in the deployed version).

This is just an issue in the English version, the Portuguese version has been altered 👍
