### ISSUE TITLE
'About Us' page

### ISSUE THREAD

**Issue by iteles** [mosteirodelandim/landim-website#19]
This new page will require a little research on competitor's pages and a better understanding of what is important to our audience.

It was agreed that this will be an introduction to the website of sorts with the following key points:
+ As it takes the top spot from the 'History' section (which was a majority vote based on the events audience but _barely_, with a 50/50 split from the _major_ decision-makers), it needs to heavily lean into the historical nature of the Mosteiro and reference the historical section
  + Note for posterity: our current history section is complete but altogether stuffy and long-winded which is why this section was agreed upon as an alternate introduction for those who _didn't_ want to get into the detail
+ There will need to be some personalisation here - it's a _family_ farm with a family feel as well as being a professional outfit and we want to make sure this comes across as well
  + There was some debate around whether we should include a family photograph, no conclusion was reached
+ It iwll be interesting to mention the various things we do and link to the relevant sections (events, grape-picking, etc)

This page will need to be:
+ [x] Created in itself following the format of the rest of the pages on the website
+ [x] Included in the tiles on the homepage #2 
+ [x] Included in the sidebar menu #1

**Comment by LuchoTurtle** [comment]
The layout of this page is essentially done. It is only missing the content, something that I have no idea to insert and has yet been decided. Should we open a new issue for the About Page, focused on its content instead?

**Comment by iteles** [comment]
@LuchoTurtle We can either keep this one open and add the content to the OP checklist or open a new issue - whichever you prefer for organising the issues ☺️
