### ISSUE TITLE
Alter content of the navigation blocks on homepage

### ISSUE THREAD

**Issue by iteles** [mosteirodelandim/landim-website#2]
Following a review of the site contents and sections as a family, some alterations are required for the navigation blocks on the homepage.

Original blocks:
![image](https://user-images.githubusercontent.com/4185328/90431118-746f1100-e0c0-11ea-8cab-795b00dabb49.png)

### Alterations required
+ [x] The navigation blocks on homepage should contain the following sections [Portuguese / English ]:
  + [x] Quem Somos / About Us **[New section, separate issue to be opened on content]**
  + [x] Serviços / Services **[Unchanged for now - a new issue will be opened on a change in title]**
  + [x] Fotografias / Photo Gallery **[Name change in English]**
  + [x] História / History **[New position in the hierarchy]**
  + [x] Jardins / Gardens **[New section, separate issue to be opened on content]**
  + [x] Vinho & Vinhas / Wine and Vineyard **[New name in both languages]**
  + [x] FAQs **[Unchanged]**
+ [x] The blocks should be displayed in the following way (keeping block sizing, style and responsiveness exactly as is currently):
![mosteirodelandim-nav-blocks](https://user-images.githubusercontent.com/4185328/90432129-01ff3080-e0c2-11ea-9b70-1533b9aeddb6.jpg)

Note: The 'Stay' portion of the website will be brought back but is currently on hold whilst we await legalization of the accommodation.

**Comment by iteles** [comment]
Not quite, I see the issue here.

I mentioned I needed to open a separate issue on the 'About Us' section but didn't get around to doing it!
I've now done this at #19 and hope it's clearer. There is a dependency on completing that issue but a photograph can be found for this tile all the same.

**Comment by LuchoTurtle** [comment]
Alrighty.  Is the "about us" part in the Landing page a tile?  Or is it a brief summary and introduction to the site, where the user needs to go to the menu to go to the dedicated page? I don't feel like this was discussed 🤔

**Comment by iteles** [comment]
The 'About Us' section that pertains to this issue is a tile on the landing page that follows the same format of the rest of the site: 
+ A tile with a background photo (needs to be landscape)
+ Contains the 'Quem Somos'/'About Us' title
+ One sentence of intro, to be written
