### ISSUE TITLE
'FAQ' Refactor

### ISSUE THREAD

**Issue by LuchoTurtle** [mosteirodelandim/landim-website#20]
Since we are having a Contact Us section on the FAQ page (and a link from the sideburger menu), we kinda need to refactor the FAQ page. As it stands, the questions _per se_ are alright but we need to do a couple more things.

- [x] Add a "contact us" section after the questions or the map. We can replace the current one (the Email and Call Us button) with a section with more relevant content.
- [x] Stretch the Google Map to cover the section (remove the "where we are" title and expand the map)

**Comment by iteles** [comment]
I have quite a few notes on this page including content changes already and will write them up/enhance the OP later today 👍
