### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by LuchoTurtle** [mosteirodelandim/landim-website#22]
Site needs a favicon. We need someone to design it. It should be fairly simple but it should match the look and feel of the website.

**Comment by iteles** [comment]
I have to speak to Susana @ saiotes tomorrow about the logo #7 so I'll ask her about vectorising a small camelia and a version of the logo for the favicon 👍

**Comment by iteles** [comment]
@LuchoTurtle Favicon criado! https://drive.google.com/drive/folders/1T0KtZcMfCb-bA7J8UKkQQZo8UiQOhW58?usp=sharing
