### ISSUE TITLE
💡 Register *NEW* Domain and Deploy this? 

### ISSUE THREAD

**Issue by nelsonic** [mosteirodelandim/landim-website#34]
Dearest @LuchoTurtle & @iteles 👋 

It's 2022 and the site still looks like this: https://www.mosteirodelandim.com/
![image](https://user-images.githubusercontent.com/194400/166909838-0b31e5d5-e05f-47ed-874c-c858fc9ee5e9.png)

And that screenshot is _favourable_, if I don't constrain the viewport the content is _lost_ on my screen:
![image](https://user-images.githubusercontent.com/194400/166912382-9eef34c2-24b9-47ee-a6a9-f747b4925128.png)

It's very "retro" ... and if that's the "look" someone is going for, then they're **`#winning`** 😜 
But we all know that it's slow to load, not mobil-optimised and we don't have visibility of the analytics / conversion rate!

# Lighthouse / PageSpeed Insights

If we run the current site through the Google Lighthouse / PageSpeed analyser: https://web.dev/measure/

![image](https://user-images.githubusercontent.com/194400/166912682-47cb1ecf-0265-4e68-b490-f5498f1e42fc.png)

Accessibility is _poor_: (_which means search engines aren't indexing the content properly either!_)
![image](https://user-images.githubusercontent.com/194400/166912666-cb2de944-7dcc-46a7-a00c-7e7e94ca5b09.png)

But it's the SEO that _really_ bothers me:
![image](https://user-images.githubusercontent.com/194400/166912782-8f19bf14-1014-410c-8d5f-5a4525a058be.png)

The Google analysis is ***objective***. Nobody can argue with the result. Zero _Debate_!
We could _easily_ achieve **100%** in all areas with the new site 
and simultaneous make it mobile-first, more engaging & _converting_!

# SEO Experiment Proposal: `NEW` Domain!

What are your thoughts on registering a **new domain** for this e.g: 
https://www.arsys.pt/dominios/pesquisar/mosteirodelandim
![image](https://user-images.githubusercontent.com/194400/166913265-938caf8f-51f5-46de-8aca-1b7d3b727852.png)

Or even a more generic **`landim.org`**  https://www.arsys.pt/dominios/pesquisar/landim
![image](https://user-images.githubusercontent.com/194400/166913395-3e4f511c-7ddb-4e32-ac7b-5356e7498499.png)

The point is: there are options! 

The experiment would cost us **`~ €50/year`** (including registration & hosting if we want to do any "backend")

## On a New Domain we could _Experiment_ ...

We could pull in photos from instagram (for better or [worse](https://github.com/dwyl/home/issues/29)) and have "reviews" which Google would pick up because we would mark them up correctly. 
Then we could pay a content person (Marketing Student) to write a few posts and get them translated into the right languages based on the Google Analytics ... 

I would _conservatively_ guess that we could get to the top of Google SERPS for "Mosteiro Landim" in _less_ than 6 months.
i.e. we could run the experiment and then "discuss" it at the next fam meeting.

## Re-integrate if it Succeeds

If we can demonstrate to the _current_ "management" that we are _literally_ throwing money away ("deitar dinheiro à rua!") 
by not updating the website, then we can make a case for _finally_ getting the "keys" to the domain!

They could either point the _existing_ domain to the new site or we could redirect to the domain from "our" experiment.

**Comment by LuchoTurtle** [comment]
Thank you @nelsonic  for putting more effort than all the "tias" combined towards the website! (I'm hoping they never visit GH so this stays between us 😉 ).

I'm 100% aware how legacy the current deployed site is and it goes without saying it's hopeless to refactor it, hence why I started developing a new website on this repo. Thing is, after stagnating (essentially _waiting_ for the tias to actually do something), I've grown more and more disgruntled with how the website turned out to be - I feel like I can do much better with the knowledge I've gained throughout the years. 

But no matter, I'm hoping to finish it, deploy and start anew whenever it's more convenient.

---

Regarding the amazing Nelson's Landim Experiment ™, I ought to admit I didn't quite *get* what we're trying to do here. I understood what we are trying to accomplish (bossing the SEO and topping SERPS) but I don't quit understand the process 😅 .

Regardless, I'm all for it! 😍

**Comment by nelsonic** [comment]
If we deploy the work you have _already_ done we can _iterate_ from there.
If we are able to prove that in 6 months a _new_ site/domain can reach the top of the Google Results and get a higher click-through / conversion than the current site, then the Admins for the _current_ ("legacy") site no longer have an excuse.

@iteles thoughts?

**Comment by nelsonic** [comment]
@LuchoTurtle somehow I doubt that any Tias will be visiting GH any time soon; they're just too _busy_ ... 🤷‍♂️ 
and if they do, for whatever reason, at leas they can see that we care about the sustainability of the venue. 📈 
Landim has so **much _potential_**, but without a **clear [business] plan + investment**, it's just _degrading_ [rapidly]. 📉 

We can discuss further when you next visit if you prefer... 💬 

But the gist is this: 
1. The current site is _horrible_ [from an accessibility/SEO/mobile perspective] and hasn't been updated in years. 🤦‍♂️ 
  > **Note**: some of the **photos** on the existing site are good, but they are all _tiny_ and not enlargeable ... 
2. You [@LuchoTurtle] have poured **_many_ hours** building a new site. 🎉  but that effort is _wasted_ if it's not _deployed_!
3. The site hasn't been published anywhere, not even a demo version. 
  So we cannot evaluate it further without running it locally ... seems wasteful.
4. If we register a **_`new`_ domain** and deploy the **`new`** site, we can be in _control_ of the analytics.

Now that M'Andy's Wedding https://github.com/LuchoTurtle/andys-wed is _finally_ done, 💍 🎉 
we can focus on other things. 🎯

**Comment by iteles** [comment]
I mean, the site is currently live [here](http://mosteirodelandim.surge.sh/), right? http://mosteirodelandim.surge.sh/

We can use this to deploy for quick review, but I'm honestly starting to think that if we + maybe Leonor review the site we can just deploy it to the ***real*** domain and a) nobody will notice; b) we won't be wasting SEO juice on a separate domain and start building ours right away 😉

**Comment by nelsonic** [comment]
SEO is only “wasted” if you don’t understand how SEO works. Having a separate domain that ranks highly is a way to *own* more of the SERPs, I.e push your competitors off the front page. And if you need to consolidate you just **301** the relevant pages to the domain you want to boost.

**Comment by LuchoTurtle** [comment]
Yeah, I'm using surge to review but you can't really do SEO with `surge.sh`, I don't think it's even indexed nor crawled. It's intended for peer review and not for the "official" site. So it makes sense to deploy to our domain already (after we double-check with Leo), I wager

**Comment by LuchoTurtle** [comment]
Done.

https://mosteirodelandim.com/

**Comment by nelsonic** [comment]
Nice one @LuchoTurtle 👌 

What is the [Call To Action](https://www.optimizely.com/optimization-glossary/call-to-action/) on this site?  💭 

![mosteirodelandim-website-no-cta](https://github.com/mosteirodelandim/landim-website/assets/194400/171810d4-f0f0-407a-b094-417ee968eec1)

**Comment by LuchoTurtle** [comment]
There's none. I've followed the same pattern there are on other quintas, such as https://portoferreira.com/en/quinta-do-porto or https://www.quintalagodoscisnes.com/.

However, if there would be one, I don't know what it should be/whether there should be one on the main page, as I don't know if it fits the design. There are CTAs on each page, though, redirecting to events and tours.

**Comment by nelsonic** [comment]
Forget what _other_ inherited and unprofitable Quintas are doing. 
If _any_ of these "businesses" had to pay for their underlying assets (land, buildings & equipment) they would all be unviable. If you - the next generation of owners - want Landim to be sustainable, you need to use every "conversion" tool in the playbook to maximise the effectiveness of your website. Not _waste_ visitors by not having an _action_ for them to perform. The main page needs to be a Landing Page similar to any KickStarter Page where you explain the Product or Service and have a _singular_ focus to get people to _start_ their journey toward booking their event. #68
