### ISSUE TITLE
Google Analytics 4

### ISSUE THREAD

**Issue by LuchoTurtle** [mosteirodelandim/landim-website#50]
Got this notification.

![image](https://user-images.githubusercontent.com/17494745/210152729-8f40d9e4-4100-48f7-9f4a-b8f1f5e5f9e4.png)

Making the switch [should be fairly easy](https://support.google.com/analytics/answer/10759417?utm_campaign=2022-q4-gbl-all-gafree&utm_source=google-growth&utm_medium=email&utm_content=ga-sunset-msa-reminder-norep-advertisers). 
Although I don't know if we are using Universal Analytics or not 🤔

**Comment by LuchoTurtle** [comment]
Trying to follow the setup wizard and use Mosteiro's Gmail account, but I don't have permission to make any changes.

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/17494745/210152900-e1351a48-5b48-4ae2-8730-e8e4a645b14d.png">

Maybe someone from Mercatura, @iteles ?

**Comment by iteles** [comment]
I think we just set this up for the new site from scratch, we don't need the mercatura stuff
