### ISSUE TITLE
"Your connection is not private" (SSL Error on www.mosteirodelandim.com ) 🔥 

### ISSUE THREAD

**Issue by nelsonic** [mosteirodelandim/landim-website#53]
I _know_ this is not the repo for the _current_/_live_ website. But I don't know where the "right" place to report this is ... 🤷‍♂️ 

When I google for Mosteiro de Landim: https://www.google.com/search?q=mosteiro+de+landim
Google rightly puts the `.com` website at the top of the SERPs:

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/194400/215191202-04b6565e-1a3d-44ee-a91b-7507d6019cfb.png">

But when I click that link, I see the following warning: https://www.mosteirodelandim.com
<img width="978" alt="image" src="https://user-images.githubusercontent.com/194400/215190666-3b50e439-f1aa-4dfe-8e49-5727392da631.png">

If I dismiss the warning I can see the page: 
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/194400/215190825-932da835-0bdb-4960-a73b-2631ff0579a3.png">

Who is responsible for updating the SSL cert?
Feels like the efforts being made in the other coms channels are kinda spoiled if the _first_ result on Google has this UX. 💭

**Comment by LuchoTurtle** [comment]
I think this is on Mercatura's side, it's where the website *I think* it's ultimately deployed.

Nonetheless, all of these issues will be resolved once the photos are sorted. We'll probably get [Let's Encrypt](https://letsencrypt.org/) and deploy it on Netlify (Surge doesn't have a free pricing plan) and deploy this site once and for all, even if it's made with Gatsby or not and will later be rebuilt with any other framework.

What matters is getting this out there, check if the SEO is gucci, check Lighthouse and then leave it for the time being.

**Comment by LuchoTurtle** [comment]
This has been fixed.

https://mosteirodelandim.com/
