### ISSUE TITLE
[Bug] Circles inside carousel should be clickable

### ISSUE THREAD

**Issue by LuchoTurtle** [mosteirodelandim/landim-website#56]
https://mosteirodelandim.surge.sh/services

<img width="328" alt="image" src="https://user-images.githubusercontent.com/17494745/218594380-066cba2c-5db2-49f8-8947-c3a003bc2728.png">

- [ ] These little circles should be clickable and drag the image to the side. 

- [ ] Auto loop in other pages.

**Comment by iteles** [comment]
The recognized user pattern is to have clickable arrows on either side or the image too
